### ISSUE TITLE
to_csv broken with dask >= 1.1

### ISSUE THREAD

**Issue by brey** [crusaderky/xarray_extras#17]
I am testing to_csv for writing big files to ascii but I get an error in the tests 

ValueError: dictionary update sequence element #0 has length 46; 2 is required.

It works when chucks are 0 but not with chunks. 

Any ideas?

py3.6.7
xarray                    0.12.1                     py_0    conda-forge
xarray-extras             0.4.1           py36h1de35cc_1000    conda-forge

**Comment by crusaderky** [comment]
Hi @brey, thanks for the feedback.
Can you post a minimal reproducible example?

**Comment by brey** [comment]
Hi @crusaderky. I created a new conda env with just
```
conda install xarray-extras
conda install pytest"
```
Then the py.test --pyargs xarray_extras fails with the above errors for chunks other than 0.

platform darwin -- Python 3.7.3, pytest-4.5.0, py-1.8.0, pluggy-0.12.0

**Comment by crusaderky** [comment]
I've reproduced the issue - it's an incompatibility with dask >=1.1. I'm working on a fix; while you wait you can downgrade dask (``conda install dask=1.0``) to work around the issue.

**Comment by crusaderky** [comment]
Fixed in xarray_extras 0.4.2
